import { test, expect } from '@playwright/test';

test('blog navigation', async ({ page }) => {
  await page.goto('https://ilarionhalushka.github.io/jekyll-ecommerce-demo/');
  await page.locator('li').filter({ hasText: 'Scar the Lion Scar the lion' }).getByRole('link').first().click();
  await page.locator('.style-picker > div').click();
  await page.getByRole('button', { name: 'Add to cart' }).click();
  await page.getByLabel('Size').selectOption('Small');
  await page.getByLabel('Increment quantity').click();
  await page.getByRole('button', { name: 'Checkout' }).click();
  await page.getByLabel('Full name').fill('Fergi');
  await page.getByLabel('Email').click();
  await page.getByLabel('Email').fill('fergi@gmail.com');
  await page.locator('.snipcart-textbox').first().click();
  await page.getByLabel('Street address').fill('Randevu11');
  await page.getByLabel('Apt/Suite').click();
  await page.getByLabel('Apt/Suite').fill('34');
  await page.getByLabel('City').click();
  await page.getByLabel('City').fill('London');
  await page.locator('.snipcart-typeahead__content > .snipcart-typeahead__select > .snipcart-typeahead__input > .snipcart-form__select-wrapper > .snipcart-textbox').click();
  await page.getByLabel('Country').fill('gre');
  await page.getByText('Greenland').click();
  await page.getByLabel('Province/State').click();
  await page.getByLabel('City').click();
  await page.getByLabel('Province/State').click();
  await page.getByLabel('Province/State').fill('London');
  await page.getByLabel('Postal/ZIP code').click();
  await page.getByLabel('Postal/ZIP code').fill('3443');
  await page.getByRole('button', { name: 'Continue to payment' }).click();
  await page.frameLocator('iframe').getByText('4242 4242 4242').click();
  await page.frameLocator('iframe').locator('body').press('Meta+c');
  await page.frameLocator('iframe').getByPlaceholder('Card number').click();
  await page.frameLocator('iframe').getByPlaceholder('Card number').fill('4242 4242 4242 4242');
  await page.frameLocator('iframe').getByPlaceholder('MM/YY').click();
  await page.frameLocator('iframe').getByPlaceholder('MM/YY').fill('12/12');
  await page.frameLocator('iframe').getByPlaceholder('CVV').click();
  await page.frameLocator('iframe').getByPlaceholder('CVV').fill('123');
  await page.getByRole('button', { name: 'Place order' }).click();
});